fixed filter dupes
bcgov/EPIC-FLOW pull request #1168
Opened 2023-11-03 23:01 UTC by TomChapmanGov

#1162

2023-11-06 20:54 UTC, jadmsaadaot requested changes
Adding date type prop

2023-11-06 20:54 UTC, jadmsaadaot commented on epictrack-web/src/components/shared/MasterTrackTable/utils.ts
> +        formatLabel(dataObject[key])
I would suggest adding an optional type prop, and if type === 'date' we do this. date keys could be other than start_date or end_date

2023-11-06 20:55 UTC, jadmsaadaot commented on epictrack-web/src/components/shared/MasterTrackTable/utils.ts
> +        formatLabel(dataObject[key])
I'm thinking even we can add a formatValue. Which could be default to () => dataOject[key]. I think this is probably a the better suggestion

2023-11-07 17:48 UTC, dinesh-aot approved these changes

2023-11-07 21:18 UTC, jadmsaadaot approved these changes

2023-11-07 22:12 UTC, merged