My Tasks Modal - remove form padding
bcgov/EPIC-FLOW pull request #2290
Opened 2024-05-27 18:57 UTC by djnunez-aot

#2201 

-Remove padding on task modal

2024-05-27 22:45 UTC, jadmsaadaot commented on epictrack-web/src/components/myTasks/MyTaskDialog.tsx
> +          padding: 0,
not great, we shouldn't override mui classes like this. Find another way

2024-05-27 22:46 UTC, jadmsaadaot requested changes
We shouldn't overwrite mui classes like this

2024-05-28 14:21 UTC, djnunez-aot commented on epictrack-web/src/components/myTasks/MyTaskDialog.tsx
> +          padding: 0,
i added a prop since this happens everywhere

2024-05-29 16:26 UTC, jadmsaadaot approved these changes

2024-05-29 16:26 UTC, merged